name: PR test
on:
  push:
    branches:
      - feat/test1
jobs:
  makePR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: test commit message
          title: test title
          body: test body
          branch: main
