name: Runner 1
on:
  pull_request:
    branches:
      - 'feat/test1'
  push:
    branches:
      - 'feat/test1'
jobs:
  meta-check:
    runs-on: ubuntu-latest #TBD
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          echo "Test1"
      - run: echo "END"
